Implementing LoadingImageView
AnnaBanani/TheMET pull request #16
Opened 2023-04-28 19:09 UTC by AnnaBanani

Implementing LoadingImageView

2023-04-28 21:17 UTC, Ssimboss requested changes

2023-04-29 10:36 UTC, AnnaBanani commented on TheMET/TheMET/Network/LoadingImageView.swift
> +    enum LoadingImageView {
fixed

2023-04-29 10:37 UTC, AnnaBanani commented on TheMET/TheMET/Network/LoadingImageView.swift
> +    private var state: LoadingImageView = .loaded(UIImage(named: "Not Loaded Image")!) {
fixed

2023-04-29 11:09 UTC, AnnaBanani commented on TheMET/TheMET/Network/LoadingImageView.swift
> +            self.failedImageView.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: 0),
fixed

2023-04-29 11:10 UTC, AnnaBanani commented on TheMET/TheMET/Network/LoadingImageView.swift
> +            self.activityIndicator.stopAnimating()
fixed

2023-04-30 12:07 UTC, Ssimboss approved these changes

2023-04-30 12:18 UTC, merged