Implementing ArtView
AnnaBanani/TheMET pull request #28
Opened 2023-06-23 19:23 UTC by AnnaBanani

Implementing ArtView

2023-06-26 13:43 UTC, Ssimboss commented on TheMET/TheMET/Extentions/UIButton+apply.swift
> +        }
If image if `nil`, button should remove its `image` for `normal` state.

2023-06-26 14:30 UTC, AnnaBanani commented on TheMET/TheMET/ArtView/ArtView.swift
> +//            self.loadingImageView.heightAnchor.constraint(equalToConstant: 150),
fixed

2023-06-27 09:30 UTC, Ssimboss requested changes

2023-06-27 09:30 UTC, Ssimboss commented on TheMET/TheMET/Extentions/UIButton+apply.swift
> +        }
There is no need to unwrap `image` in this case. It should be just set as is.

2023-06-27 15:13 UTC, merged