Properly cache Images on the disk
AnnaBanani/TheMET pull request #58
Opened 2023-08-17 18:33 UTC by AnnaBanani

Properly cache Images on the disk

2023-08-17 23:54 UTC, Ssimboss requested changes

2023-08-17 23:54 UTC, Ssimboss commented on TheMET/TheMET/Cache/ImageCache.swift
> +    private let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
This property is unused

2023-08-17 23:54 UTC, Ssimboss commented on TheMET/TheMET/Cache/ImageCache.swift
> +            guard let fileURL = self.makeFileUrl(urlString: urlString),
Don’t read file-data from the disk on main thread/queue

2023-08-17 23:54 UTC, Ssimboss commented on TheMET/TheMET/Cache/ImageCache.swift
> +        guard let fileURL = self.makeFileUrl(urlString: urlString) else { return }
Don’t write data to file on main thread/queue

2023-08-18 11:18 UTC, AnnaBanani commented on TheMET/TheMET/Cache/ImageCache.swift
> +    private let cachesDirectory = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
+

2023-08-18 11:59 UTC, Ssimboss requested changes

2023-08-18 11:59 UTC, Ssimboss commented on TheMET/TheMET/Cache/ImageCache.swift
> +                completion(image)
The completions must be executed back on main-thread.

2023-08-18 12:12 UTC, Ssimboss requested changes

2023-08-18 12:12 UTC, Ssimboss commented on TheMET/TheMET/Cache/ImageCache.swift
> +                    completion(image)
All the completions executed which are currently executed on `DispatchQueue.global` in this thread must be executed back on `main`

2023-08-18 13:36 UTC, Ssimboss approved these changes

2023-08-18 14:03 UTC, merged